import = ["/Users/sarath.lun/.config/alacritty/themes/themes/tokyo-night.toml"]

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "MesloLGS NF"

[scrolling]
# auto_scroll = true
history = 2000

[shell]
args = ["new-session"]
program = "/opt/homebrew/bin/tmux"

[window]
opacity = 1.0
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
