[general]
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[cursor]
unfocused_hollow = true
blink_timeout = 0

[cursor.style]
blinking = "Always"


[env]
TERM = "xterm-256color"


[font]
#normal.family = "MesloLGS Nerd Font Mono"
normal.family = "JetBrainsMono Nerd Font"
size = 12

[scrolling]
# auto_scroll = true
history = 2000

[window]
padding.x = 10
padding.y = 0
# decorations = "Buttonless"
opacity = 0.9
blur = true
option_as_alt = "Both"
startup_mode = "Maximized"
