import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]


[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"


[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16

[scrolling]
# auto_scroll = true
history = 2000

[shell]
args = ["new-session"]
program = "/opt/homebrew/bin/tmux"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.9
blur = true
option_as_alt = "Both"
startup_mode = "Maximized"

