[general]
import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[cursor]
unfocused_hollow = true
blink_timeout = 0

[cursor.style]
blinking = "Always"


[env]
TERM = "xterm-256color"


[font]
normal.family = "MesloLGS Nerd Font Mono"
#normal.family = "JetBrainsMono Nerd Font"
size = 16

[scrolling]
# auto_scroll = true
history = 2000

[terminal.shell]
args = ["new-session"]
program = "/opt/homebrew/bin/tmux"

[window]
padding.x = 0
padding.y = 0
# decorations = "Buttonless"
opacity = 1.0
blur = false
option_as_alt = "Both"
startup_mode = "Maximized"


